{
 "title": "App",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Game", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logins Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "login_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logouts Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "logout_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Games Exited",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "targets": [
    { "expr": "exited_games_counter", "legendFormat": "Exited Games" }
   ]
  },
  {
   "title": "Online Players",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "players_connected", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Game Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_duration_seconds_sum / clamp_min(total_ended_games, 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Games in Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "games_in_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Ended Games",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_ended_games", "legendFormat": "__auto" }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Backend Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - container_start_time_seconds{name=\"nodejs-backend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"nodejs-backend\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((increase(http_requests_total{job=\"nodejs-backend\", status=~\"4..\"}[$__range]) or vector(0))) + sum((increase(http_requests_total{job=\"nodejs-backend\", status=~\"5..\"}[$__range]) or vector(0)))) / sum((increase(http_requests_total{job=\"nodejs-backend\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[30m])) / sum(rate(http_request_duration_seconds_count[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests in Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_in_flight{job=\"nodejs-backend\", route!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"nodejs-backend\"}[5m])",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Requests by Status Code",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"nodejs-backend\"}[5m])) by (status)",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "API Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{job=\"nodejs-backend\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{job=\"nodejs-backend\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"nodejs-backend\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"nodejs-backend\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Average Duration of Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(http_request_duration_seconds_sum[1m])) / (rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  }
 ]
}