{
 "title": "Global Health",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "containers",
    "query": {
     "query": "label_values(container_should_exist,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Memory Usage (system)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (system)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage (system)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (system)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "CPU Usage (system)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) )",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "I/O Throughput (system)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[5m]) * -1",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Containers Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "container_alive", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Memory Usage (container)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{name=\"$containers\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "CPU Usage (container)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Core" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{name=\"$containers\"}[5m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum by (name) (rate(container_pressure_cpu_waiting_seconds_total{name=\"$containers\"}[5m]))",
     "legendFormat": "CPU Wait Time"
    }
   ]
  },
  {
   "title": "Uptime (container)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (name) (time() - container_start_time_seconds{name=\"$containers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Throughput (container)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{name=\"$containers\"}[5m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{name=\"$containers\"}[5m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "I/O Throughput (container)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 32 },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_fs_reads_bytes_total{name=\"$containers\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum by (name) (rate(container_fs_writes_bytes_total{name=\"$containers\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}