filebeat.inputs:
- type: filestream
  id: docker-logs
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
  parsers:
    - container:
        stream: stdout
        format: docker
  symlinks: true
  processors:
    - decode_json_fields:
        fields: ["message"]
        target: ""
        overwrite_keys: true
    - drop_fields:
        fields: ["host", "agent", "ecs", "input", "container", "@metadata"]

output.logstash:
  hosts: ["logstash:5044"]